[2023-12-03T19:40:22.415+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_scrapper.transform_and_push_Kharkiv.push_Kharkiv manual__2023-12-03T19:40:02.837435+00:00 [queued]>
[2023-12-03T19:40:22.440+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_scrapper.transform_and_push_Kharkiv.push_Kharkiv manual__2023-12-03T19:40:02.837435+00:00 [queued]>
[2023-12-03T19:40:22.448+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-03T19:40:22.501+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): transform_and_push_Kharkiv.push_Kharkiv> on 2023-12-03 19:40:02.837435+00:00
[2023-12-03T19:40:22.515+0000] {standard_task_runner.py:57} INFO - Started process 886 to run task
[2023-12-03T19:40:22.523+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_scrapper', 'transform_and_push_Kharkiv.push_Kharkiv', 'manual__2023-12-03T19:40:02.837435+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/weather_scrapper.py', '--cfg-path', '/tmp/tmp29_gcdzq']
[2023-12-03T19:40:22.531+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask transform_and_push_Kharkiv.push_Kharkiv
[2023-12-03T19:40:22.660+0000] {task_command.py:416} INFO - Running <TaskInstance: weather_scrapper.transform_and_push_Kharkiv.push_Kharkiv manual__2023-12-03T19:40:02.837435+00:00 [running]> on host 046e595e6dd8
[2023-12-03T19:40:22.822+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'transform_and_push_Kharkiv.push_Kharkiv', field 'parameters'. Template: ['Kharkiv', "{{ ti.xcom_pull(task_ids='transform_Kharkiv.process_Kharkiv')[0] }}", "{{ ti.xcom_pull(task_ids='transform_Kharkiv.process_Kharkiv')[1] }}", "{{ ti.xcom_pull(task_ids='transform_Kharkiv.process_Kharkiv')[2] }}", "{{ ti.xcom_pull(task_ids='transform_Kharkiv.process_Kharkiv')[3] }}", "{{ ti.xcom_pull(task_ids='transform_Kharkiv.process_Kharkiv')[4] }}"]
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-12-03T19:40:22.832+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-12-03T19:40:22.852+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=weather_scrapper, task_id=transform_and_push_Kharkiv.push_Kharkiv, execution_date=20231203T194002, start_date=20231203T194022, end_date=20231203T194022
[2023-12-03T19:40:22.901+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 72 for task transform_and_push_Kharkiv.push_Kharkiv (None has no element 0; 886)
[2023-12-03T19:40:22.958+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T19:40:23.048+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
